Repository hdmf-dev/hdmf-zarr, pull requests merged in 2022-08, with the labels that each got.

#33 Minor fixes and enhancements for the docs
  .gitignore
  docs/source/conf.py
  docs/source/index.rst
  docs/source/overview.rst
  src/hdmf_zarr/backend.py
  src/hdmf_zarr/utils.py
Labels: topic: docs

#34 Add badges to the README
  README.rst
Labels: priority: low, topic: docs, topic: continuous integration

#41 Update workflow for release and conda
  .github/workflows/deploy_release.yml
  .github/workflows/run_tests.yml
Labels: category: bug, priority: critical
